### ISSUE TITLE
Mudar path padrão

### ISSUE THREAD

**Issue by LuckShiba** [Takasakiii/Ena-Code#13]
O path padrão é `.`, porém seria melhor se fosse, por padrão, um path vazio, assim abrindo, por padrão, a última workspace aberta, como já é no Visual Studio Code normal.

**Comment by Takasakiii** [comment]
entao realmente não sei sobre essa mudança, por exemplo eh algo q vc curte porem para mim o melhor path eh o path `.` pois raramente eu uso o ultimo aberto.

so mudar essa característica do programa n seria a melhor solução a este caso.

**Comment by Takasakiii** [comment]
Criar quem sabe uma config, so n sei qual sera o comportamento default ainda.
